version: '3.7'

services:

  infidea-sharing-react:
    container_name: infidea-sharing-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3003:3000
    environment:
      - CHOKIDAR_USEPOLLING=true